crm_dashboard/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('vendedores', 'VendedoresController');
Route::get('vendedores/show/{id}', 'VendedoresController@show');
Route::get('vendedores/destroy/{id}', 'VendedoresController@destroy');

Route::resource('metas', 'MetasController');
Route::get('metas/update/{id}', 'MetasController@update');
Route::get('metas/destroy/{id}', 'MetasController@destroy');

Route::resource('pedidos', 'PedidosController');
Route::get('pedidos/show/{id}', 'PedidosController@show');
Route::get('pedidos/destroy/{id}', 'PedidosController@destroy');
Route::get('pedidos/update/{id}', 'PedidosController@update');

Route::resource('promocao', 'ProdutoPromocaoController');
//Route::get('promocao/show/{id}', 'ProdutoPromocaoController@show');
Route::get('promocao/destroy/{id}', 'ProdutoPromocaoController@destroy');
Route::get('promocao/update/{id}', 'ProdutoPromocaoController@update');

Route::auth();
Route::get('/home', 'HomeController@index');

crm_dashboard/app/Http/Controllers/MetasController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Request;
use App\Http\Requests;
use DB;
use Illuminate\Support\Facades\Input;
use App\Vendedores;
use Illuminate\Pagination\Paginator;
use Storage;
use Image;
use Redirect;


class MetasController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
      $metas = DB::table('meta')->select('id','valor')->orderBy('valor','desc')->paginate('10');
      return view('metas.index', compact('metas'));
    }
    public  function create()
    {
      return view('metas.form');
    }

    public  function update()
    {
      
    }
    public function destroy($id)
    {
      DB::table('meta')->where('id', '=', $id)->delete();
      return view('metas.excluido');
    }

    public function store()
    {
      $meta = Request::input('meta');
      DB::insert('insert into meta (valor) values (?)',array($meta));
      return view('metas.adicionado');
    }
}

crm_dashboard/resources/views/metas/adicionado.blade.php
@include('header')

<p class="alert alert-success">
  A Meta foi adicionado com sucesso!
</p>

crm_dashboard/resources/views/metas/excluido.blade.php
@include('header')

<p class="alert alert-success">
  Meta excluida com sucesso!
</p>

crm_dashboard/resources/views/metas/form.blade.php
@include('header')
<div class="container">
  <form action="{!!URL::route('metas.store')!!}" method="post">
    <label for="nome">Meta</label>
    <input id='currency' type="text" name="meta">
    <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
    <input class="btn btn-status" type="submit" value="Gravar">
  </form>
</div>
</div>
</div>
</div>
</div>
</body>
</html>

crm_dashboard/resources/views/metas/index.blade.php
@include('header')
    <div class="container">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4><i class="fa fa-crosshairs" aria-hidden="true"></i> Metas</h3>
        </div>
        <div class="panel-body">
      <table class="table">
          <tableheader>
            <th>Meta</th><th>Ação</th>
            @foreach ($metas as $meta)
            <tr><td><h2>R$ {{money_format('%.2n', $meta->valor)}}</h2></td><td><a href="metas/show/{{ $meta->id }}"><button type="button" name="button" class="btn btn-status"><i class="fa fa-pencil" aria-hidden="true"></i> Editar</button></a></td><td><a href="/metas/destroy/{{ $meta->id }}"><button type="button" name="button" class="btn btn-status"><i class="fa fa-trash" aria-hidden="true"></i> Excluir</button></a></td></tr>

            @endforeach
          </tableheader>
    </table>

 <a href="{!!URL::route('metas.create')!!}"><button class="btn btn-status">Cadastro</button></a>
    </div>
  </div>
</div>
  </body>
</html>