crm_dashboard/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('vendedores', 'VendedoresController');
Route::get('vendedores/show/{id}', 'VendedoresController@show');
Route::get('vendedores/destroy/{id}', 'VendedoresController@destroy');

Route::resource('metas', 'MetasController');
Route::get('metas/update/{id}', 'MetasController@update');
Route::get('metas/destroy/{id}', 'MetasController@destroy');

Route::resource('pedidos', 'PedidosController');
Route::get('pedidos/show/{id}', 'PedidosController@show');
Route::get('pedidos/destroy/{id}', 'PedidosController@destroy');
Route::get('pedidos/update/{id}', 'PedidosController@update');

Route::resource('promocao', 'ProdutoPromocaoController');
//Route::get('promocao/show/{id}', 'ProdutoPromocaoController@show');
Route::get('promocao/destroy/{id}', 'ProdutoPromocaoController@destroy');
Route::get('promocao/update/{id}', 'ProdutoPromocaoController@update');

Route::auth();
Route::get('/home', 'HomeController@index');

crm_dashboard/app/Pedidos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pedidos extends Model
{
    protect $table = 'pedidos';
    protect $table = 'metas';
    protect $table = 'vendedores';
}

crm_dashboard/app/Http/Controllers/PedidosController.php
<?php

namespace App\Http\Controllers;
use App\Pedidos;
use Illuminate\Support\Facades\Request;
use App\Http\Requests;
use DB;
use Illuminate\Support\Facades\Input;
use Illuminate\Pagination\Paginator;
use Storage;
use Image;
use Redirect;


class PedidosController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function show($id)
    {
      //$pedido = DB::table('pedidos')->select('id','id_vendedor','valor','numero','created_at')->where('id', = '$id');
      //return view('pedidos.show', compact('pedido'));
    }
    public function update()
    {

    }
    public function index()
    {
      $pedidos = DB::table('pedidos')->select('id','id_vendedor','valor','numero','created_at')->orderBy('valor','desc')->paginate('10');
      return view('pedidos.index', compact('pedidos'));

    }
    public function destroy($id)
    {
      DB::table('pedidos')->where('id', '=', $id)->delete();
      return view('pedidos.excluido');
    }
    public function CalculaMeta($meta,$pedidostotal)
    {
      $calculometa = $pedidostotal / $meta;
      return $calculometa * 100 . '%';

    }
    public function create()
    {
      $vendedores = DB::table('vendedores')->select('nome','id')->get();
      return view('pedidos.form', compact('vendedores'));
    }
    public function store()
    {
      $vendedor = Request::input('vendedor');
      $pedido = Request::input('pedido');
      $produto = Request::input('produto');
      $valor = Request::input('valor');
      $date = date('d-m-yyyy H:i:s');
      DB::insert('insert into pedidos (id_vendedor, numero, valor,produto, created_at) values (?,?,?,?,NOW())',array($vendedor, $pedido,$valor,$produto));
      return view('pedidos.adicionado');
    }
}

crm_dashboard/resources/views/pedidos/adicionado.blade.php
@include('header')

<p class="alert alert-success">
  O pedido foi adicionado com sucesso!
</p>

crm_dashboard/resources/views/pedidos/excluido.blade.php
@include('header')

<p class="alert alert-success">
  O Pedido excluido com sucesso!
</p>

crm_dashboard/resources/views/pedidos/form.blade.php
@include('header')
<div class="container">
  <div class="panel panel-default">
     <div class="panel-heading"><h4><b><i class="fa fa-user" aria-hidden="true"></i> Adicionar Pedido</b></h4></div>
  <div class="panel-body" id="dadosvendedor">
  <form action="{!!URL::route('pedidos.store')!!}" method="post">
    <label for="nome">Vendedor</label>
    <select class="" name="vendedor">
      @foreach ($vendedores as $vendedor)
      <option value="{{$vendedor->id}}">{{$vendedor->nome}}</option>
      @endforeach
    </select>
    <label for="nome">Nº Pedido</label>
    <input type="text" name="pedido" required>
    <label for="valor">Valor</label>
    <input class="valor"  id="currency" data-thousands="" data-decimal="." type="text" name="valor">
    <label for="produto">Vendeu algum produto promocional?(Quantidade)</label>
    <input class="valor" type="number" name="produto">
    <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
    <input class="btn btn-status" type="submit" value="Gravar">
  </form>
</div>
</div>
</div>
</div>
</div>
</body>
</html>

crm_dashboard/resources/views/pedidos/index.blade.php
@include('header')
<?php  setlocale(LC_MONETARY, 'pt_BR.UTF-8'); ?>
    <div class="container">
      <div class="panel panel-default">
      <div class="panel-heading">
        <h4><i class="fa fa-trophy" aria-hidden="true"></i> Pedidos</h3>
      </div>
      <div class="panel-body">
      <table class="table">
          <tableheader>
            <th>Nº Pedido</th><th>Valor</th><th>Data Emissão</th><th>Ação</th>
          </tableheader>
            <td></td>
          <tr>
            @foreach ($pedidos as $pedido)
              <td>{{$pedido->numero}}</td><td>R$ {{$pedido->valor}}</td><td>{{$pedido->created_at}}</td><td><a href="/pedidos/destroy/{{$pedido->id}}"><button class="btn btn-status"><i class="fa fa-trash" aria-hidden="true"></i> Excluir</button></a></td></tr>
            @endforeach
          </tr>
    </table>

 <a href="{!!URL::route('pedidos.create')!!}"><button class="btn btn-status">Cadastro</button></a>
    </div>
    </div>
    </div>

  </body>
</html>

crm_dashboard/resources/views/pedidos/show.blade.php
@include('header')