crm_dashboard/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('vendedores', 'VendedoresController');
Route::get('vendedores/show/{id}', 'VendedoresController@show');
Route::get('vendedores/destroy/{id}', 'VendedoresController@destroy');

Route::resource('metas', 'MetasController');
Route::get('metas/update/{id}', 'MetasController@update');
Route::get('metas/destroy/{id}', 'MetasController@destroy');

Route::resource('pedidos', 'PedidosController');
Route::get('pedidos/show/{id}', 'PedidosController@show');
Route::get('pedidos/destroy/{id}', 'PedidosController@destroy');
Route::get('pedidos/update/{id}', 'PedidosController@update');

Route::resource('promocao', 'ProdutoPromocaoController');
//Route::get('promocao/show/{id}', 'ProdutoPromocaoController@show');
Route::get('promocao/destroy/{id}', 'ProdutoPromocaoController@destroy');
Route::get('promocao/update/{id}', 'ProdutoPromocaoController@update');

Route::auth();
Route::get('/home', 'HomeController@index');

crm_dashboard/app/Vendedores.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vendedores extends Model
{
  protect $table = 'pedidos';
  protect $table = 'metas';
  protect $table = 'vendedores';
}

crm_dashboard/app/Http/Controllers/VendedoresController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Request;
use App\Http\Requests;
use DB;
use Illuminate\Support\Facades\Input;
use App\Vendedores;
use Illuminate\Pagination\Paginator;
use Storage;
use Image;
use Redirect;
use File;
use Session;
use Validator;


class VendedoresController extends Controller
{
  public function __construct()
  {
      $this->middleware('auth');
  }
  public function index()
  {
    $vendedores = DB::table('vendedores')->select('vendedores.*')->orderBy('id','desc')->paginate('5');
    return view('vendedores.index', compact('vendedores'));
  }
  public function  show($id)
  {
    $vendedores = DB::SELECT("SELECT vendedores.id,meta.valor,vendedores.nome,vendedores.avatar FROM vendedores INNER JOIN meta ON vendedores.id_meta=meta.id where vendedores.id = ?", [$id]);
    if (empty($vendedores)) {
      return 'Vendedor Não encontrado';
    }
    return view('vendedores.show')->with('v',$vendedores[0]);
  }
  public function create()
  {
    $meta = DB::table('meta')->select('id','valor')->get();
    return  view('vendedores.form', compact('meta'));
  }
  public function destroy($id)
  {
    DB::table('vendedores')->where('id', '=', $id)->delete();
    return view('vendedores.excluido');
  }
  public function store()
  {
  $nome = Request::input('nome');
  $meta = Request::input('meta');
  //$input = Input::file('image');
  $file = array('image' => Input::file('image'));
  // setting up rules
  $rules = array('image' => 'required',); //mimes:jpeg,bmp,png and for max size max:10000
  // doing the validation, passing post data, rules and the messages
  $validator = Validator::make($file, $rules);
  if ($validator->fails()) {
    // send back to the page with the input data and errors
    return Redirect::to('upload')->withInput()->withErrors($validator);
  }
  else {
    if (Input::file('image')->isValid()) {
      $destinationPath = 'uploads';
      $extension = Input::file('image')->getClientOriginalExtension();
      $fileName = rand(11111,99999).'.'.$extension;
      Input::file('image')->move($destinationPath, $fileName);
      $caminho = "/uploads/". $fileName;
      Session::flash('success', 'Upload successfully');
      DB::insert('insert into vendedores (nome, id_meta, avatar) values (?,?,?)',array($nome, $meta,$caminho));
      return Redirect::to('vendedores');
    }
    else {
      Session::flash('error', 'uploaded file is not valid');
      return Redirect::to('upload');
    }
  }
    return view('vendedores.adicionado');
  }
  public function update()
  {
    //
  }
}

crm_dashboard/resources/views/vendedores/adicionado.blade.php
@include('header')

<p class="alert alert-success">
  O Vendedor foi adicionado com sucesso!
</p>

crm_dashboard/resources/views/vendedores/excluido.blade.php
@include('header')

<p class="alert alert-success">
  O Vendedor excluido com sucesso!
</p>

crm_dashboard/resources/views/vendedores/form.blade.php
@include('header')
<div class="container">
  <div class="panel panel-default">
     <div class="panel-heading"><h4><b><i class="fa fa-user" aria-hidden="true"></i> Adicionar Vendedor</b></h4></div>
  <div class="panel-body" id="vendedor">
  <form enctype="multipart/form-data" action="{!!URL::route('vendedores.store')!!}" method="post">
    <label for="nome">Nome:</label>
    <input type="text" name="nome">
    <label for="id_meta">Meta:</label>
    <select id="currency" class="" name="meta">
      @foreach ($meta as $metas)
      <option value="{{$metas->id}}">R$ {{number_format($metas->valor,2)}}</option>
      @endforeach
    </select>
    <label for="avatar">Avatar:</label>
    <input type="file" id="image" name="image">
    <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
    <input class="btn btn-status" type="submit" value="Gravar">
  </form>
</div>
</div>
</div>
</div>
</div>
</body>
</html>

crm_dashboard/resources/views/vendedores/index.blade.php
@include('header')
    <div class="container">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4><i class="fa fa-users" aria-hidden="true"></i> Vendedores</h3>
        </div>
        <div class="panel-body">
      <table class="table">
          <tableheader>
            <th></th><th>Nome</th><th>Ação</th>
          </tableheader>
        @foreach ($vendedores as $vendedor)
        <tr><td><img src="{{$vendedor->avatar}}" width="80px" class="img-responsive img-thumbnail"/></td><td><h2>{{$vendedor->nome}}</h2></td><td><a href="vendedores/show/{{ $vendedor->id }}"><button type="button" name="button" class="btn btn-status"><i class="fa fa-pencil" aria-hidden="true"></i> Editar</button></a></td><td><a href="/vendedores/destroy/{{ $vendedor->id }}"><button type="button" name="button" class="btn btn-status"><i class="fa fa-trash" aria-hidden="true"></i> Excluir</button></a></td></tr>
      @endforeach
    </table>
      <nav>
  <ul class="pagination">
    <li>
      <a href="{{$vendedores->previousPageUrl() }}" aria-label="Previous">
        <i class="fa fa-hand-o-left" aria-hidden="true"></i> Anterior
      </a>
    </li>
    <li>
      <a href="{{$vendedores->nextPageUrl() }}" aria-label="Next">
        <i class="fa fa-hand-o-right" aria-hidden="true"></i> Próximo
      </a>
    </li>
  </ul>
  @if(empty($vendedores))
  <div class="alert alert-danger">não temos vendedores cadastrados</div>
  @else
  @endif
</nav>
 <a href="{!!URL::route('vendedores.create')!!}"><button class="btn btn-status">Cadastro</button></a>
    </div>
  </div>
  </div>
  </body>
</html>

crm_dashboard/resources/views/vendedores/show.blade.php
@include('header')
<div class="container">
  <div class="container">
      <div class="col-md-12">
        <div class="panel panel-default">        
          <div class="panel-body">
<form class="" action="index.html" method="post">
    <div class="text-center">
      <div class="item"><img  class="avatar-x2" src="{{$v->avatar}}" alt="" /></div>
      <h2>
      {{$v->nome}}
    </h2>
    </div>
    <div class="form-group">
    <h2 for="">Meta</h2>
    <h3>
      {{number_format($v->valor,2)}}
    </h3>
  </div>
  <div class="form-group">
  </div>
    <div class="form-group">
    <a href=""></a><button type="button" name="name" class="btn btn-status" value="voltar">Voltar</button></a>
  </div>
</form>
</div>
</div>
</div>
</div>

</body>
</html>
</div>